# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universitet', models.CharField(max_length=32, verbose_name='Университет')),
                ('specials', models.CharField(blank=True, max_length=32, verbose_name='Специализация')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('datestart', models.CharField(blank=True, max_length=32, verbose_name='Дата поступления')),
                ('dateend', models.CharField(blank=True, max_length=32, verbose_name='Дата окончания')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='dateend',
            field=models.CharField(blank=True, max_length=32, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='work',
            name='datestart',
            field=models.CharField(blank=True, max_length=32, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='work',
            name='duties',
            field=models.TextField(blank=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='work',
            name='period',
            field=models.PositiveIntegerField(blank=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='position',
            field=models.CharField(blank=True, max_length=16, verbose_name='Должность'),
        ),
    ]
